### ISSUE TITLE
Voice issue in ios devices

### ISSUE THREAD

**Issue by nitin-619** [philnash/mediadevices-camera-selection#19]
hello @philnash we have implemented this library but getting sound issue into ios devices like we have tested  in iphone 11, iphone 11 pro , iphone 13, And in iphone 8 and 5s its working, We are also getting issue using //sdk.twilio.com/js/video/releases/2.17.1/twilio-video.min.js javascript sdk in our application 
![room](https://user-images.githubusercontent.com/94530797/145186407-ba256943-56eb-42d5-ba49-48738f91c958.jpg)

**Comment by philnash** [comment]
Hi @nitin-619, the example in this repo is a modified version of the [Twilio Video Quickstart application available here](https://github.com/twilio/video-quickstart-js). The Quickstart version is more actively developed and more up to date with this one, which is just an example of adding camera selection to the original app. I would recommend you try with [the version in this repo](https://github.com/twilio/video-quickstart-js) and if you still have the problems with iOS, then [raise an issue there too](https://github.com/twilio/video-quickstart-js/issues).

I'll close this issue for now as your problem should be handled by using the other repo or by raising an issue there.

Thanks!
