### ISSUE TITLE
unable to switch camera on android devices

### ISSUE THREAD

**Issue by praveshkhatana** [philnash/mediadevices-camera-selection#6]
Camera selection isn't working on android devices(browser).

**Comment by philnash** [comment]
Hi @praveshkhatana, thanks for the report. Can you give me a bit more detail please? Are you seeing any error messages, for example? The more detail you can give, the more chance I can find out what's going on.

Thanks!

**Comment by praveshkhatana** [comment]
Hi @philnash, 
I am simply trying to run your code preview in the android browser. It is showing all available cameras list in the dropdown but nothing happens upon selection.

Even tried to stop `localVideotrack` before initiating `Video.createVideoTrack`

current `twilio-video version 2.3.0`
```
if (previewTracks) {
      previewTracks.forEach(function (track) {
        track.stop();
        
      });
    }
    Video.createLocalVideoTrack({
```

Error Message
<img width="487" alt="Screenshot 2020-03-22 19 15 35" src="https://user-images.githubusercontent.com/26607301/77250964-895e8a00-6c71-11ea-9f10-cbc3e58df3a4.png">

**Comment by philnash** [comment]
I haven't run this project for a while. I'll take a look and see what I find.

Does the [simple example](https://philnash.github.io/mediadevices-camera-selection/), without video chat, work for you? (Note, you have to press the button on this one to change the camera.)

**Comment by praveshkhatana** [comment]
Yes, this one is working fine on all the devices.

**Comment by praveshkhatana** [comment]
Please check it on samsung s8/s9 device.

**Comment by philnash** [comment]
I'll have to leave you to check it on the Samsung devices. I have a Motorola Moto G4 for Android testing. Will be looking at this soon.

**Comment by philnash** [comment]
Ok, I've pushed [an update](https://github.com/philnash/mediadevices-camera-selection/commit/77ce837e76ce191a1825fe7362e7f4c0678e9448#diff-d7fee9d9546b8711aa88849b95759548) that seemed to work for me. Give it a test and see what happens.

**Comment by praveshkhatana** [comment]
Thanks @philnash, finally it's fixed
