### ISSUE TITLE
Unable to switch camera in Iphone XS

### ISSUE THREAD

**Issue by bhagyalakshmisabbella** [philnash/mediadevices-camera-selection#8]
trackSubscribed function is not getting triggered when i try to flip the camera in Iphone XS mobile. Please let me know if i need to update any of this code.

Thanks in advance

**Comment by philnash** [comment]
Hi @bhagyalakshmisabbella,

I just ran the video chat and was able to change my cameras on my iPhone XS.

Do you have any more details? Are there any errors thrown if you debug iPhone Safari with the desktop app?

**Comment by bhagyalakshmisabbella** [comment]
Thanks for your prompt response.

Let me explain the issue comprehensively,

Person1 is using iphone XS safari and Person2 is using desktop app.

Person1 is in video chat with person2. While person1 is using his front camera for chat, video is visible to both the persons. When the person1 is switching to rear camera for chat, video is visible to person1 only, person2 cannot able to see the rear camera video.  

My primary analysis:
I observed remote tracks are not getting added when person1 switches to rear camera. Again if Person1 switching back to front camera, remote and local tracks are getting added.

Can you please check and suggest me to resolve the issue.

**Comment by philnash** [comment]
Have you changed the code at all?

I was able to run this and correctly switch cameras from my iPhone. Do you see any errors in the developer tools in either application?

**Comment by bhagyalakshmisabbella** [comment]
@philnash 
I was trying with the same code. When I try to flip the front camera to rear camera & vice versa continuously above 5 times, the remote track is not getting added on the other side. I am facing this problem in every ios device (not on android). Didn't observed any JavaScript errors when I debug it. 

Please check this issue.

**Comment by philnash** [comment]
Just to confirm, this only happens when you flip the camera back and forth several times?
Do you allow the camera to load and be seen on the other side each time you flip it?

**Comment by bhagyalakshmisabbella** [comment]
@philnash 
Yes. It is happening when flipping several times. I am allowing the cameras to load for 2 minutes, even though it is not working.

Please look into this issue.

**Comment by philnash** [comment]
Hi @bhagyalakshmisabbella, I am afraid I cannot reproduce this issue.

I just connected to a room from my iPhone changed the cameras several times and each time they appeared for the other participant in the room. I was also able to change that participant's cameras too and they showed up on the iPhone as expected.

Is there anything else about this you can tell me? What version of iOS are you using? Are you able to debug this yourself at all? Do you see the messages in the on screen log that show when video tracks are added and removed? 

I'm at a bit of a loss, since I am unable to reproduce this myself.

**Comment by bhagyalakshmisabbella** [comment]
![log](https://user-images.githubusercontent.com/20061048/78866241-a5796e00-7a5c-11ea-9bcc-18cae877d157.png)

@philnash 
Please check the attached log image which will show you the track is removed and not added again when i flip the camera.

**Comment by philnash** [comment]
Ok, looks like the tracks are adding and removing correctly. Can you help with my other questions?

> Is there anything else about this you can tell me? What version of iOS are you using? Are you able to debug this yourself at all? Perhaps you can inspect the tracks that are loaded onto the page and see why they are not appearing in the video, or if you can get them to appear somehow? 

I really can't help more than make suggestions because this is not failing for me.

**Comment by bhagyalakshmisabbella** [comment]
@philnash 
We have added one second of timeout before creating the local video tracks. It works like charm.

setTimeout( function(){ 
                        alert(" Changing camera...");
			Video.createLocalVideoTrack({
      			deviceId: { exact: select.value }}).then(function(localVideoTrack) {
                                     localParticipant.publishTrack(localVideoTrack);
                                     log(localParticipant.identity + ' added track: ' + localVideoTrack.kind);
                                     const previewContainer = document.getElementById('local-media');
                                     attachTracks([localVideoTrack], previewContainer); }); 
}, 1000);

**Comment by philnash** [comment]
I'm glad you found something that works for you!

**Comment by philnash** [comment]
Hey, the video team had actually been looking into this and there was an issue in track negotiaton. They have worked on and [merged a fix here](https://github.com/twilio/twilio-video.js/pull/1000) and it looks like it will be in the next release, 2.5.0. Hopefully the timeout will help for now, but make sure to upgrade as soon as you can to get the latest.
